service: cloud-runtime-python-empty

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7 # or python3.7, supported as of November 2018

functions:
  empty:
    handler: handler.empty
    events:
      - http:
          path: ping
          method: get


